OY-3952
Opetushallitus/konfo-ui pull request #377
Opened 2022-12-22 11:12 UTC by tatu1

React-router-dom v6 ja SiteImprove-skripti

2023-01-02 11:49 UTC, SalamaGofore requested changes
404

2023-01-02 11:49 UTC, SalamaGofore commented on src/main/app/src/App.js
> +        path="koulutus/:oid"
404:sta ei tule jos urli on sopivalla tavalla väärä: https://testiopintopolku.fi/konfo/fi/aaaaakoulutus/1.2.246.562.13.00000000000000001022

404 tulee vastaavalla urlilla kuitenkin untuvalla

2023-01-04 08:57 UTC, tatu1 commented on src/main/app/src/App.js
> +        path="koulutus/:oid"
Tuo oli vähän muuttunut V6:sessa. Path lisätty.

2023-01-05 08:07 UTC, SalamaGofore approved these changes

2023-01-05 08:45 UTC, merged