OPHJOD-127: Uusi hakutulos-tagi contentful-sivuille
Opetushallitus/konfo-ui pull request #477
Opened 2023-12-05 15:00 UTC by pitkamak

2023-12-07 09:14 UTC, heidilm requested changes

2023-12-07 09:14 UTC, heidilm commented on src/main/app/src/components/common/EntiteettiKortti.tsx
> +          padding: isSmall ? '16px' : '32px',
Tän vois varmaan siirtää tyylimäärittelyihin tiedoston alkuun `.paperRoot`-luokan alle, niin ei tarvi toistaa tässä ja Entiteettikortissa.

2023-12-07 09:14 UTC, heidilm commented on src/main/app/src/components/common/EntiteettiKortti.tsx
> +        </Box>
Tästä vois tehä oman komponenttinsa vaikka samaan tiedostoon ja käyttää sitä sekä Entiteettikortissa ja tässä EntiteettiKorttiTiivistetyssä, kun näyttäisi olevan identtinen koodin pätkä.

2023-12-08 08:35 UTC, pitkamak commented on src/main/app/src/components/common/EntiteettiKortti.tsx
> +          padding: isSmall ? '16px' : '32px',
Tuon paddingin siirsin paperRootin alle, mutta tuo borderTop on värien osalta erilainen tavallisella ja tiivistetyllä.

2023-12-08 09:45 UTC, heidilm approved these changes

2023-12-11 11:11 UTC, merged